import { Response, NextFunction } from 'express';
import { AuthRequest } from '../middleware/auth.middleware';
import { supabaseService } from '../services/supabase.service';
import { zipExporter } from '../utils/zipExporter';
import { createError } from '../middleware/error.middleware';
import { logger } from '../utils/logger';
class ExportController {
  async exportAsZip(req: AuthRequest, res: Response, next: NextFunction) {
    try {
      const project = await supabaseService.getProjectById(req.params.projectId, req.user!.id);
      if (!project) throw createError('Project not found', 404);
      const files = await supabaseService.getProjectFiles(req.params.projectId);
      if (!files?.length) throw createError('No files to export', 400);
      const safeName = project.name.replace(/[^a-zA-Z0-9-_]/g, '_').slice(0, 64);
      res.setHeader('Content-Type', 'application/zip');
      res.setHeader('Content-Disposition', `attachment; filename="${safeName}.zip"`);
      await zipExporter.streamZip(files, res);
    } catch (err) { next(err); }
  }
  async exportAsMarkdown(req: AuthRequest, res: Response, next: NextFunction) {
    try {
      const project = await supabaseService.getProjectById(req.params.projectId, req.user!.id);
      if (!project) throw createError('Project not found', 404);
      const files = await supabaseService.getProjectFiles(req.params.projectId);
      let md = `# ${project.name}\n\n${project.description || ''}\n\n`;
      for (const f of files) md += `## \`${f.file_path}\`\n\n\`\`\`${f.language}\n${f.content}\n\`\`\`\n\n`;
      res.setHeader('Content-Type', 'text/markdown');
      res.setHeader('Content-Disposition', `attachment; filename="${project.name}.md"`);
      res.send(md);
    } catch (err) { next(err); }
  }
  async exportAsJson(req: AuthRequest, res: Response, next: NextFunction) {
    try {
      const project = await supabaseService.getProjectById(req.params.projectId, req.user!.id);
      if (!project) throw createError('Project not found', 404);
      const files = await supabaseService.getProjectFiles(req.params.projectId);
      res.json({ project: { name: project.name, type: project.type }, files: files.map((f: { file_path: string; content: string; language: string }) => ({ path: f.file_path, content: f.content, language: f.language })), meta: { generator: 'ClaudGPT', creator: 'Emmanuel ARIYO', company: 'EMEMZYVISUALS DIGITALS' } });
    } catch (err) { next(err); }
  }
  async exportReadme(req: AuthRequest, res: Response, next: NextFunction) {
    try {
      const project = await supabaseService.getProjectById(req.params.projectId, req.user!.id);
      if (!project) throw createError('Project not found', 404);
      const readme = `# ${project.name}\n\n> Generated by ClaudGPT — EMEMZYVISUALS DIGITALS\n\n## Setup\n\n\`\`\`bash\nnpm install\nnpm run dev\n\`\`\`\n`;
      res.setHeader('Content-Type', 'text/markdown');
      res.setHeader('Content-Disposition', 'attachment; filename="README.md"');
      res.send(readme);
    } catch (err) { next(err); }
  }
  async validateExport(req: AuthRequest, res: Response, next: NextFunction) {
    try {
      const project = await supabaseService.getProjectById(req.params.projectId, req.user!.id);
      if (!project) throw createError('Project not found', 404);
      const files = await supabaseService.getProjectFiles(req.params.projectId);
      const result = zipExporter.validate(files);
      const stats = zipExporter.getStats(files);
      res.json({ valid: result.valid, stats, validation: { errors: result.errors, warnings: result.warnings } });
    } catch (err) { next(err); }
  }
  async previewExport(req: AuthRequest, res: Response, next: NextFunction) {
    try {
      const project = await supabaseService.getProjectById(req.params.projectId, req.user!.id);
      if (!project) throw createError('Project not found', 404);
      const files = await supabaseService.getProjectFiles(req.params.projectId);
      res.json({ projectName: project.name, stats: zipExporter.getStats(files), files: files.map((f: { file_path: string; language: string; content: string }) => ({ path: f.file_path, language: f.language, sizeBytes: Buffer.byteLength(f.content || '', 'utf8') })) });
    } catch (err) { next(err); }
  }
}
export const exportController = new ExportController();
