import { Router } from 'express';
import { authController } from '../controllers/auth.controller';
import { authMiddleware } from '../middleware/auth.middleware';
const router = Router();
router.post('/signup', authController.signup);
router.post('/login', authController.login);
router.post('/logout', authMiddleware, authController.logout);
router.get('/me', authMiddleware, authController.getMe);
router.post('/refresh', authController.refreshToken);
router.post('/oauth/google', authController.googleOAuth);
router.post('/oauth/github', authController.githubOAuth);
export default router;
